### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Pranav18262** [iam-NVN/SDMN_CheckerBot#1]
This repo have some issues 

Can't be deployed to heroku needs somw fixes

Dev should try once to deploy :D

**Comment by iam-NVN** [comment]
The Repo is fine I suppose. I deployed it to Heroku and it worked perfectly fine. There is a separate branch for Heroku. Check that out

**Comment by iam-NVN** [comment]
Try Deploying now, fixed the buildpack issue
