### ISSUE TITLE
Lol

### ISSUE THREAD

**Issue by nub-af** [iam-NVN/SDMN_CheckerBot#5]
https://github.com/iam-NVN/SDMN_CheckerBot/blob/6fd774408868319bf1a2c71a3bd851f9bccfc473/modules/checker/ss.php#L206

This may not be Approved everytime 😌 

Sir please fix it , (by replacing "Approved" with $message or $response, idk what , i am not familiar with this api so)

**Comment by iam-NVN** [comment]
It's a sample gate made for example.. You have to replace it with your site
